local RECOIL = 3 -- For RECOIL
local RECOIL_Keyboard = nil

EnablePrimaryMouseButtonEvents(true);

local KAOS = falseB
local kaos = 0

function OnEvent(event, arg)

  if (event == "MOUSE_BUTTON_PRESSED" and arg == RECOIL) or (event == "G_PRESSED" and arg == RECOIL_Keyboard) then
    KAOS = not KAOS
    kaos = arg
    if (KAOS == false) then
      OutputLogMessage("Macro OFF\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("Macro ON (RECOIL)\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
  end

  elseif (event == "MOUSE_BUTTON_PRESSED" and arg == ARS) or (event == "G_PRESSED" and arg == ARS_Keyboard) then
    KAOS = not KAOS
    kaos = arg
    if (KAOS == false) then
      OutputLogMessage("Macro OFF\n")
      if IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
    else
      OutputLogMessage("Macro ON (ARS)\n")
      if not IsKeyLockOn("capslock") then
        PressAndReleaseKey("capslock")
      end
  end

end

------------------------------| Don't touch this! |------------------------------
if kaos == RECOIL or kaos == RECOIL_Keyboard then
  if KAOS then
    repeat
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,7)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,7)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,7)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,8)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,7)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(7,7)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-7,-7)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,6)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,6)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,3)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,3)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,4)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,5)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,2)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,1)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(-5,-5)
      Sleep(10) 
      MoveMouseRelative(0,3)
      Sleep(10) 
      MoveMouseRelative(5,5)
      Sleep(10) 
      MoveMouseRelative(-5,-5)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(0,3)
      Sleep(10) 
    if not IsMouseButtonPressed(1) then break end
    until not IsMouseButtonPressed(1)
  end
end
-----------------------------------------------------------------------------------------------------
if kaos == ARS or kaos == ARS_Keyboard then
  if KAOS then
    repeat
      Sleep(12) 
    if not IsMouseButtonPressed(1) then break end
      MoveMouseRelative(7,7)
      Sleep(12) 
      MoveMouseRelative(-7,-7)
      Sleep(12) 
      MoveMouseRelative(0,5)
      Sleep(12) 
      MoveMouseRelative(7,7)
      Sleep(12) 
      MoveMouseRelative(-7,-7)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,5)
      Sleep(12) 
      MoveMouseRelative(9,7)
      Sleep(12) 
      MoveMouseRelative(-7,-7)
      Sleep(12) 
      MoveMouseRelative(0,4)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(8,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(8,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(12) 
      MoveMouseRelative(8,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(8,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-7,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-7,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-7,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-7,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-4,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,3)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(2,2)
      Sleep(14) 
      MoveMouseRelative(7,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(2,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(1,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(2,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(2,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(2,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
    if not IsMouseButtonPressed(1) then break end
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,2)
      Sleep(14) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
    if not IsMouseButtonPressed(1) then break end
      Sleep(12) 
      MoveMouseRelative(5,5)
      Sleep(12) 
      MoveMouseRelative(-5,-5)
      Sleep(12) 
      MoveMouseRelative(0,1)
      Sleep(12) 
    if not IsMouseButtonPressed(1) then break end
    until not IsMouseButtonPressed(1)
  end
end
-----------------------------------------------------------------------------------------------------
end